#          Copyright Tom Westerhout 2017.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)


language: cpp

sudo: false

# We need Ubuntu 14.04 rather than 12.04 to get latest compilers
dist: trusty

python: "3.6"


os:
  - linux
  - osx

branches:
  only:
    - development

env:
  global:
    - BOOST_ROOT=${HOME}/boost-trunk
    - SPHINX_ROOT=${HOME}/sphinx-trunk
    - BREATHE_ROOT=${HOME}/breathe-trunk
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true


matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    ############################################################################
    # Builds with GCC
    ############################################################################
    # - os: linux
    #   env: TOOLSET=gcc COMPILER=g++-6 CXXFLAGS="-std=c++14" BENCHMARK=true
    #   addons:
    #     apt:
    #       packages:
    #         - g++-6
    #         - gnuplot
    #       sources:
    #         - ubuntu-toolchain-r-test

    # - os: linux
    #   env: TOOLSET=gcc COMPILER=g++-6 CXXFLAGS="-std=c++1z" BENCHMARK=false
    #   addons:
    #     apt:
    #       packages:
    #         - g++-6
    #       sources:
    #         - ubuntu-toolchain-r-test

    # - os: linux
    #   env: TOOLSET=gcc COMPILER=g++-7 CXXFLAGS="-std=c++14" BENCHMARK=true
    #   addons:
    #     apt:
    #       packages:
    #         - g++-7
    #         - gnuplot
    #       sources:
    #         - ubuntu-toolchain-r-test

    # - os: linux
    #   env: TOOLSET=gcc COMPILER=g++-7 CXXFLAGS="-std=c++1z" BENCHMARK=false
    #   addons:
    #     apt:
    #       packages:
    #         - g++-7
    #       sources:
    #         - ubuntu-toolchain-r-test

    ############################################################################
    # Builds with Clang
    ############################################################################
    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXFLAGS="-std=c++14" BENCHMARK=true
      addons:
        apt:
          packages:
            - clang-3.8
            - g++-7
            - gnuplot
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXFLAGS="-std=c++14" BENCHMARK=true
      addons:
        apt:
          packages:
            - clang-3.9
            - g++-7
            - gnuplot
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXFLAGS="-std=c++1z" BENCHMARK=false
      addons:
        apt:
          packages:
            - clang-3.9
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-4.0 CXXFLAGS="-std=c++14" BENCHMARK=true
      addons:
        apt:
          packages:
            - clang-4.0
            - g++-7
            - gnuplot
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    # Buggy build :(
    # - os: linux
    #   env: TOOLSET=clang COMPILER=clang++-4.0 CXXFLAGS="-std=c++1z" BENCHMARK=false
    #   addons:
    #     apt:
    #       packages:
    #         - clang-4.0
    #         - g++-7
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-trusty-4.0

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-5.0 CXXFLAGS="-std=c++14" BENCHMARK=false
      addons:
        apt:
          packages:
            - clang-5.0
            - gnuplot
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty

    # - os: linux
    #   env: TOOLSET=clang COMPILER=clang++-5.0 CXXFLAGS="-std=c++1z" BENCHMARK=false
    #   addons:
    #     apt:
    #       packages:
    #         - clang-5.0
    #         - g++-7
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-trusty

    ############################################################################
    # Builds with XCode
    ############################################################################
    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXFLAGS="-std=c++14" BENCHMARK=false
      osx_image: xcode9

    # - os: osx
    #   env: TOOLSET=clang COMPILER=clang++ CXXFLAGS="-std=c++1z" BENCHMARK=false
    #   osx_image: xcode9
    # - os: osx
    #   env: TOOLSET=clang COMPILER=clang++ CXXFLAGS="-std=c++14" BENCHMARK=true
    #   osx_image: xcode8.3

    # - os: osx
    #   env: TOOLSET=clang COMPILER=clang++ CXXFLAGS="-std=c++1z" BENCHMARK=false
    #   osx_image: xcode8.3

  allow_failures:
    - os: linux
      env: COMPILER=clang++-3.9

before_install:
  - |
    if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
      brew install python3
    fi
  - python3 --version
  - pip install --user sphinx
  # - >
  #   git clone --recursive -b stable
  #   https://github.com/sphinx-doc/sphinx ${SPHINX_ROOT}
  # - cd ${SPHINX_ROOT}
  # - python3 setup.py build
  # - export PYTHONPATH="${SPHINX_ROOT}/build/lib:${PYTHONPATH}"

  # - >
  # - git clone --recursive -b master
  # - https://github.com/michaeljones/breathe ${BREATHE_ROOT}
  # - cd ${BREATHE_ROOT}
  # - python3 setup.py build
  # - export PYTHONPATH="${BREATHE_ROOT}/build/lib:${PYTHONPATH}"

  - git clone --depth 1 https://github.com/boostorg/boost.git ${BOOST_ROOT}
  - cd ${BOOST_ROOT}
    # For now, let StaticViews explicitly depend on two libraries: Boost.Core 
    # and Boost.Config. We thus get the following dependency "tree"
    # 
    # boost/config <--+-- boost/detail
    #                 |-- boost/assert
    #                 |-- boost/core
    #                 +-- boost/type_traits
    #
    # boost/core   <--+-- boost/assert
    #                 |-- boost/config
    #                 |-- boost/predef
    #                 |-- boost/static_assert
    #                 +-- boost/type_traits
    # Hence
  - git submodule update --init tools/build
  - git submodule update --init libs/assert
  - git submodule update --init libs/config
  - git submodule update --init libs/core
  - git submodule update --init libs/detail
  - git submodule update --init libs/predef
  - git submodule update --init libs/static_assert
  - git submodule update --init libs/type_traits  


install:
  - |
    # While StaticViews is not meant to be a complete Boost library, assume
    # for a minute that it it.
    cd ${BOOST_ROOT}
    mkdir libs/static_views
    cp -r ${TRAVIS_BUILD_DIR}/* libs/static_views/
  - ./bootstrap.sh
  - ./b2 headers
  - git config --global user.name "Travis bot"
  - git config --global user.email "<>"


script:
  - |
    echo "using ${TOOLSET} : : ${COMPILER} : <cxxflags>\"${CXXFLAGS}\" ;" \
      > ~/user-config.jam
  - rm -vf ${BOOST_ROOT}/libs/static_views/test/optimisation/results/*
  - rm -vf ${BOOST_ROOT}/libs/static_views/test/benchmarks/results/*
  - ./b2 libs/static_views/test toolset=$TOOLSET
  - |
    if [[ $BENCHMARK == "true" ]]; then
      { for i in {1..10}; do sleep 300; echo "No! Don't terminate me!"; done; } &
      ./b2 libs/static_views/test/benchmarks toolset=$TOOLSET
    fi


after_script:
  - |
    [[ ${TRAVIS_OS_NAME} == "osx" ]] && exit 0
    cd ${BOOST_ROOT}/libs/static_views
    # Suppress output to avoid leaking the token when the command fails
    git clone https://twesterhout:${GITHUB_TOKEN}@github.com/BoostGSoC17/static-views \
      --branch=gh-pages gh_pages_repo &>/dev/null
    if [[ "${BENCHMARK}" == "true" ]]; then
      cp -v test/benchmarks/results/*.png gh_pages_repo/test/benchmarks/results/
    fi
    cp -v test/optimisation/results/*.xml gh_pages_repo/test/optimisation/results/
    pushd gh_pages_repo/doc
    make html
    git add --all _build
    popd
    pushd gh_pages_repo/test
    git add --all .
    git commit --allow-empty -m "Update test results for ${COMPILER} to ${TRAVIS_COMMIT}"
    # Suppress output to avoid leaking the token
    travis_retry git push origin gh-pages &>/dev/null
    popd
